apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: etnair
type: Opaque
data:
  POSTGRES_USER: ZXRuYWlyX3VzZXI=
  POSTGRES_PASSWORD: ZXRuYWlyX3Bhc3M=
  POSTGRES_DB: ZXRuYWlyX2Ri
