apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZXRuYWlyX3VzZXI=        # Base64 de "etnair_user"
  POSTGRES_PASSWORD: ZXRuYWlyX3Bhc3M=    # Base64 de "etnair_pass"
  POSTGRES_DB: ZXRuYWlyX2Ri              # Base64 de "etnair_db"
